apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cbc-certificate
  namespace: dev
spec:
  domains:
    - cbcdev.accelero.com

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cbc-certificate
  namespace: prod
spec:
  domains:
    - cbc.accelero.com

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cbc
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cbcdev
    networking.gke.io/managed-certificates: cbc-certificate
  namespace: dev
spec:
  backend:
    serviceName: cbc-service
    servicePort: 80

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cbc
  annotations:
    kubernetes.io/ingress.global-static-ip-name: cbc
    networking.gke.io/managed-certificates: cbc-certificate
  namespace: prod
spec:
  backend:
    serviceName: cbc-service
    servicePort: 80
